version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./_nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./_nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./app/static:/code/static
      - ./app/media:/code/media

  postgres:
    container_name:  postgres-db
    image:           postgres:11
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8   

  web: &web
    container_name: app
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=161.35.198.20
      - VIRTUAL_PORT=8015
      - HTTP_PORT=8015
      - DEBUG=False
      - STATS_PORT=8001
      - LANG=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./app:/code
      - ./uwsgi.ini:/conf/uwsgi.ini
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8015:8015"
  
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    restart: "always"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

  celery:
    restart: "always"
    build: .
    container_name: celery
    env_file: .env
    environment:
      - LANG=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    command: celery --app=app.celery:app worker -B --loglevel=INFO
    volumes:
      - .:/src
    links:
      - redis
      - postgres
    depends_on:
      - "redis"
      - "postgres"

networks:
  default:
    external:
      name: nginx-proxy